version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: "in-out"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "inout1234"
    ports:
      - "5432:5432"
    restart: always