spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
# disable spring security's basic auth
security:
  basic:
    enabled: false
# debug true for development
debug: true
# set bindings for SQL
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
# jwt token configuration
jwt:
  key: ${JWT_KEY}
  access-token-expiration: 60000
  refresh-token-expiration: 300000
# openai configuration
openai:
  token: ${OPENAI_API_KEY}
  organization: ${OPENAI_ORGANIZATION}