spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  flyway:
    enabled: true
# disable spring security's basic auth
security:
  basic:
    enabled: false
# debug true for development
debug: true
# set bindings for SQL
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
# jwt token configuration
jwt:
  key: ${JWT_KEY}
  access-token-expiration: 604800000
  refresh-token-expiration: 18144000000
# openai configuration
openai:
  token: ${OPENAI_API_KEY}
  organization: ${OPENAI_ORGANIZATION}
# Social Login Configuration
auth:
  google:
    ios-client-id: ${GOOGLE_IOS_CLIENT_ID}

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET:inout-local}
      region: ${AWS_REGION:ap-northeast-2}
      credentials:
        access-key: ${AWS_S3_ACCESS_KEY}
        secret-key: ${AWS_S3_SECRET_KEY}
