version: '3.9'

services:
  in-out-db:
    image: mongo:8.0.9
    container_name: in-out-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--bind_ip_all", "--auth"]
    restart: unless-stopped
    networks:
      - in-out-network

  api:
    container_name: in-out-api
    image: in-out-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/src
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_KEY=${JWT_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ORGANIZATION=${OPENAI_ORGANIZATION}
      - GOOGLE_IOS_CLIENT_ID=${GOOGLE_IOS_CLIENT_ID}
      - AWS_S3_ACCESS_KEY=${AWS_S3_ACCESS_KEY}
      - AWS_S3_SECRET_KEY=${AWS_S3_SECRET_KEY}
      - JOBRUNR_DB_URI=${JOBRUNR_DB_URI}
    depends_on:
      - in-out-db
    networks:
      - in-out-network

networks:
  in-out-network:
    driver: bridge

volumes:
  mongo-data: